config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :dashboard do
    collection do
      get :upload_users
      get :upload_transactions
    end
  end

  resources :documents do
    collection do
      get :upload_users
      get :upload_transactions
      post :import_user
      post :import_transactions
      get :user_report
      get :transaction_report
      get :filter_data
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
	# mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  	# validates :name, presence: true # Make sure the owner's name is present.
end

app/models/document.rb
class Document < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :transactions
	validates_uniqueness_of :mobile
	validates_presence_of :mobile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @admin = Admin.last
  end

  def upload_users
    respond_to do |format|
      format.html { render layout: 'upload_files' }
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def upload_users
  end

  def upload_transactions
    
  end

  def user_report
  end

  def transaction_report
  end

  def filter_data
    text = params[:text]
    @type = params[:type]
    current_time = Time.current.beginning_of_day
    if text == 'Yesterday'
      end_date = start_date = Time.current.beginning_of_day - 1.day
      prev_end_date = prev_start_date = current_time - 2.days
    elsif text == 'Last 7 Days'
      prev_end_date = start_date = current_time - 7.days
      end_date = current_time
      prev_start_date = current_time - 14.days
    elsif text == 'Last 30 Days'
      prev_end_date = start_date = current_time - 30.days
      end_date = current_time
      prev_start_date = current_time - 60.days
    elsif text == 'Last 90 Days'
      prev_end_date = start_date = current_time - 90.days
      end_date = current_time
      prev_start_date = current_time - 180.days
    else
      prev_end_date = start_date = current_time.beginning_of_year
      end_date = current_time
      prev_start_date = current_time.prev_year.beginning_of_year
    end
    report_stat(@type, start_date, end_date, prev_start_date, prev_end_date)
  end

  def import_user
    @incoming_file = params[:file]
    user_id = 1
    FileUtils.mv @incoming_file.tempfile, "/home/dell/Documents/thrive/temp_file/user_#{user_id}"
    UploadUserFileJob.perform_later("/home/dell/Documents/thrive/temp_file/user_#{user_id}")
    redirect_to documents_path, notice: 'Data Imported Sucessfully'
  end

  def import_transactions
    @incoming_file = params[:file]
    user_id = 1
    FileUtils.mv @incoming_file.tempfile, "/home/dell/Documents/thrive/temp_file/transactions_#{user_id}"
    UploadTransactionFileJob.perform_later("/home/dell/Documents/thrive/temp_file/transactions_#{user_id}")
    redirect_to documents_path, notice: 'Data Imported Sucessfully'
  end

  def destroy
  end

  private

  def report_stat(type, start_date, end_date, prev_start_date, prev_end_date)
    if type == 'user'
      current_user = User.where(created_at: start_date..end_date).size
      prev_user = User.where(created_at: prev_start_date..prev_end_date).size
      difference = current_user - prev_user
      @percent_diff = (difference % prev_user) * 100
    else
      current_transaction = Transaction.where(created_at: start_date..end_date).size
      prev_transaction = Transaction.where(created_at: prev_start_date..prev_end_date).size
      difference = current_transaction - prev_transaction
      @percent_diff = (difference % prev_transaction) * 100
    end
  end

  def document_params
    params.require(:documet).permit(:name, :attachment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'csv'
  def index
    @users = User.all
    # UploadUserFileJob.perform_later('123')
  end

  # def import
  #   @incoming_file = params[:file]
  #   user_id = 1
  #   FileUtils.mv @incoming_file.tempfile, "/home/dell/Documents/thrive/temp_file/user_#{user_id}"
  #   UploadUserFileJob.perform_later("/home/dell/Documents/thrive/temp_file/user_#{user_id}")
  #   redirect_to documents_path, notice: 'Data Imported Sucessfully'
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h1 style="text-align: center;">Welcome</h1>
<div id="dashboard-details" style="border: 50px solid #aaa;padding: 300px;">
	<div class="row">
		<div class="col-md-5">
			<b>Navigate to Document page to upload data</b>
			<%= link_to "Upload Document", documents_path(admin_id: @admin.id), class: "btn btn-primary" %>
		</div>
		<div class="col-md-2"></div>
		<div class="col-md-4">
			<b>See Reports</b>
			<ul>
				<li><%= link_to "User Report", user_report_documents_path(admin_id: @admin.id, report_type: 'user'), class: "btn btn-primary" %></li><br>
				<li><%= link_to "Transaction Report", transaction_report_documents_path(admin_id: @admin.id, report_type: 'transaction'), class: "btn btn-primary" %></li>
			</ul>
		</div>
	</div>
</div>

app/views/documents/_filter_index.html.erb
<label for="time_interval">Please Select Duration:</label>
<% current_date = Date.current %>
<select name="time_interval" id="time_interval">
	<option></option>
  <option value="<%= current_date.yesterday %>">Yesterday</option>
  <option value="<%= current_date - 7.days %>">Last 7 Days</option>
  <option value="<%= current_date - 30.days %>">Last 30 Days</option>
  <option value="<%= current_date - 90.days %>">Last 90 Days</option>
  <option value="<%= current_date %>">Last Year</option>
</select>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script type="text/javascript">
	$('#time_interval').on('change', function() {
		text = $('#time_interval option:selected').text()
		type = '<%= params[:report_type] %>'
		val = $('#time_interval').val()
		$.ajax({
	    type : 'get',
	    url: '/documents/filter_data',
	    data: {
	      text: text,
	      type: type,
	      remote: "true"
	    },
	  })
	})
</script>

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/filter_data.html.erb
<b>User increase or decrease data</b>
<strong><%= @percent_diff %></strong>

app/views/documents/index.html.erb
<%= link_to "Back", dashboard_index_path, class: "btn btn-primary" %>

<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />
<br><br>
<%= link_to "Upload Users File", upload_users_documents_path(admin_id: params[:admin_id], type: 'user'), class: "btn btn-primary" %>
<br />
<br />

<%= link_to "Upload Transaction File", upload_transactions_documents_path(admin_id: params[:admin_id], type: 'transaction'), class: "btn btn-primary" %>

app/views/documents/transaction_report.html.erb
<%= render partial: 'filter_index.html.erb' %>

app/views/documents/upload_transactions.html.erb
<%= link_to "Back", documents_path(admin_id: params[:admin_id]), class: "btn btn-primary" %><br><br>
<h4>Import Data</h4>
<div class="row">
	<%= form_tag import_transactions_documents_path, multipart: true do %>
		<%= file_field_tag :file %><br><br>
		<%= hidden_field_tag 'user[admin_id]', params[:admin_id] %>
		<%= hidden_field_tag 'user[upload]', 'transaction' %>
		<%= submit_tag 'Import CSV' %>
	<% end %>
</div>

<script type="text/javascript">
	
</script>

app/views/documents/upload_users.html.erb
<%= link_to "Back", documents_path(admin_id: params[:admin_id]), class: "btn btn-primary" %><br><br>
<h4>Import Data</h4>
<div class="row">
	<%= form_tag import_user_documents_path, multipart: true do %>
		<%= file_field_tag :file %><br><br>
		<%= hidden_field_tag 'user[admin_id]', params[:admin_id] %>
		<%= hidden_field_tag 'user[upload]', 'user' %>
		<%= submit_tag 'Import CSV' %>
	<% end %>
</div>

<script type="text/javascript">
	
</script>

app/views/documents/user_report.html.erb
<%= render partial: 'filter_index.html.erb' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   
   <head>
      <title>Welcome</title>
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
   </head>
   
   <body>
      <div class = "container" style = "padding-top:20px;">
         <%= yield %>
      </div>
   </body>

</html>

app/views/users/import.html.erb
<h1>Users#import</h1>
<p>Find me in app/views/users/import.html.erb</p>

app/views/users/index.html.erb
<%= link_to "Back", documents_path(admin_id: params[:admin_id]), class: "btn btn-primary" %><br><br>
<h4>Import Data</h4>
<div class="row">
	<%= form_tag users_import_path, multipart: true do %>
		<%= file_field_tag :file %><br><br>
		<%= hidden_field_tag 'user[admin_id]', params[:admin_id] %>
		<%= hidden_field_tag 'user[upload]', 'user' %>
		<%= submit_tag 'Import CSV' %>
	<% end %>
</div>

<script type="text/javascript">
	
</script>